### Scrape of Footystats.org CSV file ID's using Selenium to manipulate login credentials
https://footystats.org/download-stats-csv
#### The footystats.org website is a comprehensive subscription based soccer data repository. This code demonstrates a Selenium library based python script to overcome login/password requirements to access its API and retrieve chosen csv files, organize the data to user requirements and save to a specific named excel sheet for further processing. This is an example of a first stage data collection and transformation procedure for a soccer auto pricing strategy.

In [1]:
# Import required libraries
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select  
import pandas as pd
import time

pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None  

USERNAME = '..add_username_here..'
PASSWORD = '..add_passwrod_here..' 
# Insert the path of chromedriver, Selenium works best via Chrome browser (downloaded from https://sites.google.com/a/chromium.org/chromedriver/downloads)
CHROMEDRIVER_PATH = 'C:\\Users\\Documents\\Python\\chromedriver.exe' 
driver = webdriver.Chrome(executable_path=CHROMEDRIVER_PATH)  
driver.get('https://footystats.org/login');
search_box = driver.find_element('name','username') 
search_box.send_keys(USERNAME)
search_box = driver.find_element('name','password') 
search_box.send_keys(PASSWORD)
driver.find_element('id','register_account').submit() 

# Downlaod Premier league season matches for our sample
matches = driver.get('https://footystats.org/c-dl.php?type=matches&comp=7704'); 

#Access the now downloaded file and convert to a data frame
df = pd.read_csv('C:\\Users\\Downloads\\england-premier-league-matches-2022-to-2023-stats.csv')

driver.quit()

C:\Users\MikeD\AppData\Local\Temp\ipykernel_13884\3647335275.py:14: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=CHROMEDRIVER_PATH)

In [2]:
# check the df
df.head()

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),home_ppg,away_ppg,home_team_goal_count,away_team_goal_count,total_goal_count,total_goals_at_half_time,home_team_goal_count_half_time,away_team_goal_count_half_time,home_team_goal_timings,away_team_goal_timings,home_team_corner_count,away_team_corner_count,home_team_yellow_cards,home_team_red_cards,away_team_yellow_cards,away_team_red_cards,home_team_first_half_cards,home_team_second_half_cards,away_team_first_half_cards,away_team_second_half_cards,home_team_shots,away_team_shots,home_team_shots_on_target,away_team_shots_on_target,home_team_shots_off_target,away_team_shots_off_target,home_team_fouls,away_team_fouls,home_team_possession,away_team_possession,Home Team Pre-Match xG,Away Team Pre-Match xG,team_a_xg,team_b_xg,average_goals_per_match_pre_match,btts_percentage_pre_match,over_15_percentage_pre_match,over_25_percentage_pre_match,over_35_percentage_pre_match,over_45_percentage_pre_match,over_15_HT_FHG_percentage_pre_match,over_05_HT_FHG_percentage_pre_match,over_15_2HG_percentage_pre_match,over_05_2HG_percentage_pre_match,average_corners_per_match_pre_match,average_cards_per_match_pre_match,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1659726000,Aug 05 2022 - 7:00pm,complete,25286.0,Crystal Palace,Arsenal,Anthony Taylor,1,0.0,0.0,1.33,2.33,0,2,2,1,0,1,NaN,"20,85",3,5,1,0,2,0,0,1,1,1,11,11,3,3,8,8,16,11,56,44,0.0,0.0,1.35,1.27,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,3.29,3.49,2.09,1.29,1.90,3.25,6.75,1.80,1.95,Selhurst Park (London)
1,1659785400,Aug 06 2022 - 11:30am,complete,NaN,Fulham,Liverpool,Andy Madley,1,0.0,0.0,1.47,0.87,2,2,4,1,1,0,"32,72","64,80",4,4,2,0,0,0,1,1,0,0,10,12,4,4,6,8,7,9,33,67,0.0,0.0,1.23,1.50,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,9.05,5.40,1.34,1.15,1.66,2.43,4.10,1.91,1.91,Craven Cottage (London)
2,1659794400,Aug 06 2022 - 2:00pm,complete,NaN,AFC Bournemouth,Aston Villa,Peter Bankes,1,0.0,0.0,1.27,1.40,2,0,2,1,1,0,"2,80",NaN,5,5,3,0,3,0,2,1,2,1,6,10,4,2,2,8,18,16,34,66,0.0,0.0,0.80,1.08,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,3.10,3.53,2.30,1.35,1.95,3.66,7.50,1.80,1.95,Vitality Stadium (Bournemouth- Dorset)
3,1659794400,Aug 06 2022 - 2:00pm,complete,NaN,Leeds United,Wolverhampton Wanderers,Robert Jones,1,0.0,0.0,1.33,0.73,2,1,3,2,1,1,"24,74",6,6,4,2,0,0,0,1,1,0,0,14,16,4,7,10,9,13,9,40,60,0.0,0.0,1.51,1.96,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,2.30,3.58,3.07,1.34,2.03,3.62,7.50,1.80,1.95,Elland Road (Leeds- West Yorkshire)
4,1659794400,Aug 06 2022 - 2:00pm,complete,52245.0,Newcastle United,Nottingham Forest,Simon Hooper,1,0.0,0.0,2.07,0.40,2,0,2,0,0,0,"58,78",NaN,11,1,0,0,3,0,0,0,2,1,24,6,10,2,14,4,9,14,61,39,0.0,0.0,2.93,0.71,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.68,3.76,4.97,1.35,1.94,3.73,7.50,2.00,1.75,St. James' Park (Newcastle upon Tyne)

In [3]:
# check the column names within the df
df.columns

Index(['timestamp', 'date_GMT', 'status', 'attendance', 'home_team_name',
       'away_team_name', 'referee', 'Game Week', 'Pre-Match PPG (Home)',
       'Pre-Match PPG (Away)', 'home_ppg', 'away_ppg', 'home_team_goal_count',
       'away_team_goal_count', 'total_goal_count', 'total_goals_at_half_time',
       'home_team_goal_count_half_time', 'away_team_goal_count_half_time',
       'home_team_goal_timings', 'away_team_goal_timings',
       'home_team_corner_count', 'away_team_corner_count',
       'home_team_yellow_cards', 'home_team_red_cards',
       'away_team_yellow_cards', 'away_team_red_cards',
       'home_team_first_half_cards', 'home_team_second_half_cards',
       'away_team_first_half_cards', 'away_team_second_half_cards',
       'home_team_shots', 'away_team_shots', 'home_team_shots_on_target',
       'away_team_shots_on_target', 'home_team_shots_off_target',
       'away_team_shots_off_target', 'home_team_fouls', 'away_team_fouls',
       'home_team_possession', 'away_team_possession',
       'Home Team Pre-Match xG', 'Away Team Pre-Match xG', 'team_a_xg',
       'team_b_xg', 'average_goals_per_match_pre_match',
       'btts_percentage_pre_match', 'over_15_percentage_pre_match',
       'over_25_percentage_pre_match', 'over_35_percentage_pre_match',
       'over_45_percentage_pre_match', 'over_15_HT_FHG_percentage_pre_match',
       'over_05_HT_FHG_percentage_pre_match',
       'over_15_2HG_percentage_pre_match', 'over_05_2HG_percentage_pre_match',
       'average_corners_per_match_pre_match',
       'average_cards_per_match_pre_match', 'odds_ft_home_team_win',
       'odds_ft_draw', 'odds_ft_away_team_win', 'odds_ft_over15',
       'odds_ft_over25', 'odds_ft_over35', 'odds_ft_over45', 'odds_btts_yes',
       'odds_btts_no', 'stadium_name'],
      dtype='object')

In [4]:
# remove unnecessary columns
df.drop(['timestamp',
         'attendance',
         'referee',
         'Pre-Match PPG (Home)',
         'Pre-Match PPG (Away)',
         'away_ppg',
         'home_ppg',
         'total_goals_at_half_time',
         'home_team_goal_count_half_time',
         'away_team_goal_count_half_time',
         'home_team_goal_timings',
         'away_team_goal_timings',
         'home_team_yellow_cards',
         'away_team_yellow_cards',
         'home_team_first_half_cards',
         'away_team_first_half_cards',
         'home_team_second_half_cards',
         'away_team_second_half_cards',
         'Home Team Pre-Match xG',
         'Away Team Pre-Match xG',
         'average_goals_per_match_pre_match',
         'btts_percentage_pre_match',
         'over_15_percentage_pre_match',
         'over_25_percentage_pre_match',
         'over_35_percentage_pre_match',
         'over_45_percentage_pre_match',
         'over_15_HT_FHG_percentage_pre_match',
         'over_05_HT_FHG_percentage_pre_match',
         'over_15_2HG_percentage_pre_match',
         'over_05_2HG_percentage_pre_match',
         'average_corners_per_match_pre_match',
         'average_cards_per_match_pre_match',
         'odds_ft_over15',
         'odds_ft_over35',
         'odds_btts_yes',
         'odds_btts_no',
         'odds_ft_over45',
         'stadium_name'],axis = 1, inplace = True)
df.head()

,date_GMT,status,home_team_name,away_team_name,Game Week,home_team_goal_count,away_team_goal_count,total_goal_count,home_team_corner_count,away_team_corner_count,home_team_red_cards,away_team_red_cards,home_team_shots,away_team_shots,home_team_shots_on_target,away_team_shots_on_target,home_team_shots_off_target,away_team_shots_off_target,home_team_fouls,away_team_fouls,home_team_possession,away_team_possession,team_a_xg,team_b_xg,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over25
0,Aug 05 2022 - 7:00pm,complete,Crystal Palace,Arsenal,1,0,2,2,3,5,0,0,11,11,3,3,8,8,16,11,56,44,1.35,1.27,3.29,3.49,2.09,1.90
1,Aug 06 2022 - 11:30am,complete,Fulham,Liverpool,1,2,2,4,4,4,0,0,10,12,4,4,6,8,7,9,33,67,1.23,1.50,9.05,5.40,1.34,1.66
2,Aug 06 2022 - 2:00pm,complete,AFC Bournemouth,Aston Villa,1,2,0,2,5,5,0,0,6,10,4,2,2,8,18,16,34,66,0.80,1.08,3.10,3.53,2.30,1.95
3,Aug 06 2022 - 2:00pm,complete,Leeds United,Wolverhampton Wanderers,1,2,1,3,6,4,0,0,14,16,4,7,10,9,13,9,40,60,1.51,1.96,2.30,3.58,3.07,2.03
4,Aug 06 2022 - 2:00pm,complete,Newcastle United,Nottingham Forest,1,2,0,2,11,1,0,0,24,6,10,2,14,4,9,14,61,39,2.93,0.71,1.68,3.76,4.97,1.94

In [5]:
df.columns

Index(['date_GMT', 'status', 'home_team_name', 'away_team_name', 'Game Week',
       'home_team_goal_count', 'away_team_goal_count', 'total_goal_count',
       'home_team_corner_count', 'away_team_corner_count',
       'home_team_red_cards', 'away_team_red_cards', 'home_team_shots',
       'away_team_shots', 'home_team_shots_on_target',
       'away_team_shots_on_target', 'home_team_shots_off_target',
       'away_team_shots_off_target', 'home_team_fouls', 'away_team_fouls',
       'home_team_possession', 'away_team_possession', 'team_a_xg',
       'team_b_xg', 'odds_ft_home_team_win', 'odds_ft_draw',
       'odds_ft_away_team_win', 'odds_ft_over25'],
      dtype='object')

In [6]:
## rename column headers for ease of use
df.rename(columns={
    'home_team_name':'Home',
    'away_team_name':'Away',
    'Game Week':'GW',
    'home_team_goal_count':'HTG',
    'away_team_goal_count':'ATG',
    'total_goal_count':'TG',
    'home_team_corner_count':'HC',
    'away_team_corner_count':'AC',
    'home_team_red_cards':'HR',
    'away_team_red_cards':'AR',
    'home_team_shots':'HS',
    'away_team_shots':'AS',
    'home_team_shots_on_target':'HST',
    'away_team_shots_on_target':'AST',
    'home_team_shots_off_target':'HSoT',
    'away_team_shots_off_target':'ASoT',
    'home_team_fouls':'HF',
    'away_team_fouls':'AF',
    'home_team_possession':'HPos',
    'away_team_possession':'APos',
    'team_a_xg':'H_xg',
    'team_b_xg':'A_xg',
    'odds_ft_home_team_win':'HOdds',
    'odds_ft_draw':'XOdds',
    'odds_ft_away_team_win':'AOdds',
    'odds_ft_over25':'O2.5'},inplace=True)
df.head()

,date_GMT,status,Home,Away,GW,HTG,ATG,TG,HC,AC,HR,AR,HS,AS,HST,AST,HSoT,ASoT,HF,AF,HPos,APos,H_xg,A_xg,HOdds,XOdds,AOdds,O2.5
0,Aug 05 2022 - 7:00pm,complete,Crystal Palace,Arsenal,1,0,2,2,3,5,0,0,11,11,3,3,8,8,16,11,56,44,1.35,1.27,3.29,3.49,2.09,1.90
1,Aug 06 2022 - 11:30am,complete,Fulham,Liverpool,1,2,2,4,4,4,0,0,10,12,4,4,6,8,7,9,33,67,1.23,1.50,9.05,5.40,1.34,1.66
2,Aug 06 2022 - 2:00pm,complete,AFC Bournemouth,Aston Villa,1,2,0,2,5,5,0,0,6,10,4,2,2,8,18,16,34,66,0.80,1.08,3.10,3.53,2.30,1.95
3,Aug 06 2022 - 2:00pm,complete,Leeds United,Wolverhampton Wanderers,1,2,1,3,6,4,0,0,14,16,4,7,10,9,13,9,40,60,1.51,1.96,2.30,3.58,3.07,2.03
4,Aug 06 2022 - 2:00pm,complete,Newcastle United,Nottingham Forest,1,2,0,2,11,1,0,0,24,6,10,2,14,4,9,14,61,39,2.93,0.71,1.68,3.76,4.97,1.94

In [7]:
df.columns

Index(['date_GMT', 'status', 'Home', 'Away', 'GW', 'HTG', 'ATG', 'TG', 'HC',
       'AC', 'HR', 'AR', 'HS', 'AS', 'HST', 'AST', 'HSoT', 'ASoT', 'HF', 'AF',
       'HPos', 'APos', 'H_xg', 'A_xg', 'HOdds', 'XOdds', 'AOdds', 'O2.5'],
      dtype='object')

In [8]:
# chech data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date_GMT  380 non-null    object
 1   status    380 non-null    object
 2   Home      380 non-null    object
 3   Away      380 non-null    object
 4   GW        380 non-null    int64
 5   HTG       380 non-null    int64
 6   ATG       380 non-null    int64
 7   TG        380 non-null    int64
 8   HC        380 non-null    int64
 9   AC        380 non-null    int64
 10  HR        380 non-null    int64
 11  AR        380 non-null    int64
 12  HS        380 non-null    int64
 13  AS        380 non-null    int64
 14  HST       380 non-null    int64
 15  AST       380 non-null    int64
 16  HSoT      380 non-null    int64
 17  ASoT      380 non-null    int64
 18  HF        380 non-null    int64
 19  AF        380 non-null    int64
 20  HPos      380 non-null    int64
 21  APos      380 non-null    int64
 22  H_xg      380 non-null    float64
 23  A_xg      380 non-null    float64
 24  HOdds     380 non-null    float64
 25  XOdds     380 non-null    float64
 26  AOdds     380 non-null    float64
 27  O2.5      380 non-null    float64
dtypes: float64(6), int64(18), object(4)
memory usage: 83.2+ KB

In [9]:
# create new df just with completed matches
df_complete = df[df['status']=='complete']

In [10]:
# check the last rows of the df to make sure status for all matches is 'incomplete'
df.tail()

,date_GMT,status,Home,Away,GW,HTG,ATG,TG,HC,AC,HR,AR,HS,AS,HST,AST,HSoT,ASoT,HF,AF,HPos,APos,H_xg,A_xg,HOdds,XOdds,AOdds,O2.5
375,May 28 2023 - 3:30pm,incomplete,Everton,AFC Bournemouth,38,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0.0,0.0,0.0,0.0,0.0,0.0
376,May 28 2023 - 3:30pm,incomplete,Leeds United,Tottenham Hotspur,38,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0.0,0.0,0.0,0.0,0.0,0.0
377,May 28 2023 - 3:30pm,incomplete,Leicester City,West Ham United,38,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0.0,0.0,0.0,0.0,0.0,0.0
378,May 28 2023 - 3:30pm,incomplete,Manchester United,Fulham,38,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0.0,0.0,0.0,0.0,0.0,0.0
379,May 28 2023 - 3:30pm,incomplete,Southampton,Liverpool,38,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
# remove status column for completed match df
df_complete.drop(['status'],axis=1,inplace=True)

In [12]:
# check team names, make sure will be compatible for future processing
df['Home'].unique()

array(['Crystal Palace', 'Fulham', 'AFC Bournemouth', 'Leeds United',
       'Newcastle United', 'Tottenham Hotspur', 'Everton',
       'Leicester City', 'Manchester United', 'West Ham United',
       'Aston Villa', 'Arsenal', 'Brighton & Hove Albion',
       'Manchester City', 'Southampton', 'Wolverhampton Wanderers',
       'Brentford', 'Nottingham Forest', 'Chelsea', 'Liverpool'],
      dtype=object)

In [15]:
# The data frame is now organized for our needs, now save it to a specific sheet within a current excel workbook
with pd.ExcelWriter('C:\\Users\\Documents\\Auto_Pricer_Prem_22_23.xlsx', engine="openpyxl", mode="a",if_sheet_exists="overlay") as writer:
    df_complete.to_excel(writer, sheet_name="Import_All", index=False)
print('Saved successfully')

Saved successfully

In [16]:
# Store the last round of fixtures with market prices for analysis
# firstly isolate the fixtures in a new df
last_round = df_complete['GW'].max()
df_last_round = df_complete[df_complete['GW'] == last_round]
df_last_round

,date_GMT,Home,Away,GW,HTG,ATG,TG,HC,AC,HR,AR,HS,AS,HST,AST,HSoT,ASoT,HF,AF,HPos,APos,H_xg,A_xg,HOdds,XOdds,AOdds,O2.5
287,Apr 08 2023 - 11:30am,Manchester United,Everton,30,2,0,2,10,4,0,0,30,16,12,2,18,14,10,9,64,36,3.25,1.48,1.44,4.33,7.00,1.73
288,Apr 08 2023 - 2:00pm,Aston Villa,Nottingham Forest,30,2,0,2,1,8,0,0,9,8,4,3,5,5,7,17,65,35,1.12,0.93,1.70,3.70,5.00,1.85
289,Apr 08 2023 - 2:00pm,Brentford,Newcastle United,30,1,2,3,6,5,0,0,14,12,6,7,8,5,10,15,41,59,1.65,1.57,3.10,3.25,2.30,2.00
290,Apr 08 2023 - 2:00pm,Fulham,West Ham United,30,0,1,1,11,4,0,0,15,13,4,7,11,6,2,4,76,24,2.00,1.63,2.65,3.10,2.70,2.15
291,Apr 08 2023 - 2:00pm,Leicester City,AFC Bournemouth,30,0,1,1,6,6,0,0,17,19,5,5,12,14,2,4,51,49,1.63,1.92,1.75,3.60,4.75,1.87
292,Apr 08 2023 - 2:00pm,Tottenham Hotspur,Brighton & Hove Albion,30,2,1,3,3,7,0,0,8,10,4,5,4,5,16,13,35,65,1.03,1.44,2.40,3.25,2.90,1.91
293,Apr 08 2023 - 2:00pm,Wolverhampton Wanderers,Chelsea,30,1,0,1,8,8,0,0,11,14,5,2,6,12,15,9,38,62,1.42,1.40,4.00,3.40,1.91,2.00
294,Apr 08 2023 - 4:30pm,Southampton,Manchester City,30,1,4,5,0,10,0,0,4,11,2,9,2,2,6,10,27,73,0.53,1.70,12.00,5.25,1.28,1.60
295,Apr 09 2023 - 1:00pm,Leeds United,Crystal Palace,30,1,5,6,2,4,0,0,12,13,8,9,4,4,11,8,48,52,1.66,1.85,2.51,3.69,2.28,2.05
296,Apr 09 2023 - 3:30pm,Liverpool,Arsenal,30,2,2,4,5,4,0,0,17,8,7,6,10,2,11,11,59,41,2.02,1.35,2.50,3.65,2.80,1.80

In [17]:
# save last round to same excel workbook, different sheet
with pd.ExcelWriter('C:\\Users\\Documents\\Auto_Pricer_Prem_22_23.xlsx', engine="openpyxl", mode="a",if_sheet_exists="overlay") as writer:
    df_last_round.to_excel(writer, sheet_name="Import_Last_Rnd", index=False)
print('Saved successfully')

Saved successfully

In [18]:
# Store next round of matches for next stage pricing. Isolate matches with rows status'incomplete' 
# create new df just with matches yet to be played
df_incomplete = df[df['status']=='incomplete']

In [19]:
# create variable 'next_round' consisting of the Game Week number located at index [0,4] for the next set of matches
# We want the next two rounds 
next_round = df_incomplete.iloc[0,4]
df_next_rounds1 = df_incomplete[(df_incomplete['GW'] == next_round)] 
df_next_rounds2 = df_incomplete[(df_incomplete['GW'] == next_round +1 )]

In [20]:
# combine the rounds
df_next_rounds = pd.concat([df_next_rounds1,df_next_rounds2])
# isolate only the columns we want
df_next_rounds = df_next_rounds[['date_GMT','Home','Away']]
df_next_rounds

                  date_GMT                     Home                     Away
297  Apr 15 2023 - 11:30am              Aston Villa         Newcastle United
298   Apr 15 2023 - 2:00pm                  Chelsea   Brighton & Hove Albion
299   Apr 15 2023 - 2:00pm                  Everton                   Fulham
300   Apr 15 2023 - 2:00pm              Southampton           Crystal Palace
301   Apr 15 2023 - 2:00pm        Tottenham Hotspur          AFC Bournemouth
302   Apr 15 2023 - 2:00pm  Wolverhampton Wanderers                Brentford
303   Apr 15 2023 - 4:30pm          Manchester City           Leicester City
304   Apr 16 2023 - 1:00pm          West Ham United                  Arsenal
305   Apr 16 2023 - 3:30pm        Nottingham Forest        Manchester United
306   Apr 17 2023 - 7:00pm             Leeds United                Liverpool
307   Apr 21 2023 - 7:00pm                  Arsenal              Southampton
309  Apr 22 2023 - 11:30am                   Fulham             Leeds United
310   Apr 22 2023 - 2:00pm                Brentford              Aston Villa
311   Apr 22 2023 - 2:00pm           Crystal Palace                  Everton
312   Apr 22 2023 - 2:00pm           Leicester City  Wolverhampton Wanderers
313   Apr 22 2023 - 2:00pm                Liverpool        Nottingham Forest
315   Apr 23 2023 - 1:00pm          AFC Bournemouth          West Ham United
316   Apr 23 2023 - 1:00pm         Newcastle United        Tottenham Hotspur

In [21]:
# Save to the the same excel workbook, different sheet
with pd.ExcelWriter('C:\\Users\\Documents\\Auto_Pricer_Prem_22_23.xlsx', engine="openpyxl", mode="a",if_sheet_exists="overlay") as writer:
    df_next_rounds.to_excel(writer, sheet_name="Import_Next_Rnd", index=False)
print('Saved successfully')

Saved successfully

This script can be set to execute once or twice each week via the Task Scheduler providing a constantly up to date workbook.